/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인. Access Token 응답 + Refresh Token 쿠키
         * @description 성공하면 Set-Cookie로 refreshToken(HttpOnly, SameSite=Strict, Path=/api/v1/auth/token)을 내려준다.
         *     같은 아이디의 기존 로그인(세션·토큰)은 모두 끊는다 (NF-LG-02).
         */
        post: operations["login"];
        /** 로그아웃. Refresh Token 폐기, 쿠키 삭제 */
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 토큰 재발급 (Refresh Token 쿠키 사용, 한 번 쓰면 교체) */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 정보 + 메뉴 트리 + 권한 목록 (메뉴 노출·버튼 활성화용) */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 내 정보 수정 */
        put: operations["updateMyInfo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 비밀번호 변경
         * @description 성공하면 이 관리자의 다른 로그인(세션·Refresh Token)을 모두 끊고,
         *     현재 로그인을 이어가도록 새 Access Token과 새 Refresh Token 쿠키를 준다.
         */
        put: operations["changeMyPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/common/codes/{groupCd}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 그룹코드의 상세코드 목록 (코드 콤보용) */
        get: operations["getCodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/common/codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 여러 그룹코드의 상세코드를 한 번에 */
        get: operations["getCodesByGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 그룹코드 목록 (SCR-COD-01 왼쪽, 페이징 없음) */
        get: operations["listCodeGroups"];
        put?: never;
        /** 그룹코드 등록 (COD-02) */
        post: operations["createCodeGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code-groups/{groupCd}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupCd: components["parameters"]["GroupCd"];
            };
            cookie?: never;
        };
        /** 그룹코드 상세 (수정 팝업) */
        get: operations["getCodeGroup"];
        /** 그룹코드 수정 (COD-03). groupCd는 무시, 시스템 코드는 useYn 무시 */
        put: operations["updateCodeGroup"];
        post?: never;
        /** 그룹코드 삭제 (COD-04). 시스템 코드·상세코드 있으면 불가 */
        delete: operations["deleteCodeGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code-groups/{groupCd}/codes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupCd: components["parameters"]["GroupCd"];
            };
            cookie?: never;
        };
        /** 상세코드 목록 (COD-05, 정렬 순서 오름차순) */
        get: operations["listCodes"];
        put?: never;
        /** 상세코드 등록 (COD-06) */
        post: operations["createCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code-groups/{groupCd}/codes/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupCd: components["parameters"]["GroupCd"];
                code: string;
            };
            cookie?: never;
        };
        get?: never;
        /** 상세코드 수정 (COD-07). code는 무시 */
        put: operations["updateCode"];
        post?: never;
        /** 상세코드 삭제 (COD-08). 시스템 코드 그룹이면 불가. 실제 삭제 */
        delete: operations["deleteCode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 전체 메뉴 트리 (MNU-01). 사용 안 함 메뉴도 포함 */
        get: operations["getMenuTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/check-menu-cd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 메뉴 코드 중복 확인 */
        get: operations["checkMenuCd"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 메뉴 등록 (MNU-03). 같은 상위 메뉴의 맨 뒤 순서가 되고, 화면 메뉴는 사용 액션만큼 권한이 생긴다 */
        post: operations["createMenu"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 순서 저장 (MNU-06). 상위 메뉴별 하위 메뉴 목록을 빠짐없이 보낸다 */
        put: operations["saveMenuOrder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/{menuId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menuId: components["parameters"]["MenuId"];
            };
            cookie?: never;
        };
        /** 메뉴 상세 (MNU-02) */
        get: operations["getMenu"];
        /**
         * 메뉴 수정 (MNU-04). 액션을 빼면 회수되는 역할을 돌려준다
         * @description dryRun=Y면 저장하지 않고 회수될 역할만 돌려준다 (프론트는 이 결과로 확인창을 띄운다).
         *     시스템 메뉴·게시판 자동 메뉴는 메뉴명·아이콘만 바꿀 수 있다.
         */
        put: operations["updateMenu"];
        post?: never;
        /** 메뉴 삭제 (MNU-07). 권한과 역할 매핑도 함께 지운다 */
        delete: operations["deleteMenu"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/{menuId}/parent": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menuId: components["parameters"]["MenuId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 상위 메뉴 변경 (MNU-05). 새 상위 메뉴의 맨 뒤 순서가 된다 */
        patch: operations["moveMenu"];
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 역할 목록 (ROL-01). 페이징 없음, 등록순 */
        get: operations["listRoles"];
        put?: never;
        /** 역할 등록 (ROL-03). 권한은 상세 화면에서 설정한다 */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/check-role-cd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 역할 코드 중복 확인 */
        get: operations["checkRoleCd"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        /** 역할 상세 (ROL-02) */
        get: operations["getRole"];
        /**
         * 역할 정보 수정 (ROL-05). 역할 코드는 바꿀 수 없다
         * @description 시스템 역할·내 역할은 ROLE_NOT_EDITABLE. 사용 안 함으로 바꾸면 그 역할의 권한이 최종 권한에서 빠진다 (BR-07)
         */
        put: operations["updateRole"];
        post?: never;
        /** 역할 삭제 (ROL-07). 부여된 관리자가 없을 때만. 권한 매핑도 함께 지운다 */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{roleId}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        /** 권한 탭 (ROL-02). 메뉴 트리 × 액션 */
        get: operations["getRolePermissions"];
        /**
         * 권한 설정 (ROL-06). 목록에 없는 메뉴는 권한을 모두 회수한다
         * @description 서버도 READ 자동 부여 규칙(BR-03)을 다시 적용한다. 내가 갖지 않은 권한을 추가하면 PRIVILEGE_ESCALATION
         */
        put: operations["saveRolePermissions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{roleId}/admins": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        /** 관리자 탭 (ROL-02). 이 역할을 가진 관리자 */
        get: operations["getRoleAdmins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{roleId}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 역할 복사 (ROL-04). 원본의 설명·권한을 그대로 가진 새 역할 (사용 여부 Y) */
        post: operations["copyRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            /** @enum {object|null} */
            data: never | null;
            error: components["schemas"]["ErrorBody"];
        };
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** @description 화면에 그대로 보여 줄 수 있는 문장 */
            message: string;
            fieldErrors: components["schemas"]["FieldError"][];
        };
        FieldError: {
            /** @description 요청 필드 이름 */
            field: string;
            message: string;
        };
        /**
         * @description 성공 응답의 error는 항상 null
         * @enum {object|null}
         */
        NullError: never | null;
        PageMeta: {
            page: number;
            size: number;
            /** Format: int64 */
            totalCount: number;
            totalPages: number;
        };
        /** @enum {string} */
        YnFlag: "Y" | "N";
        /**
         * @description 한국 시간 일시, 초 단위, 시간대 표기 없음 (docs/06-api-spec.md 1절). 동시 수정 방지의 modDt도 이 형식
         * @example 2026-10-04T14:30:15
         */
        DateTime: string;
        /** @enum {string} */
        ErrorCode: "VALIDATION_ERROR" | "INVALID_REQUEST" | "UNAUTHORIZED" | "TOKEN_EXPIRED" | "REFRESH_FAILED" | "LOGIN_FAILED" | "FORBIDDEN" | "PASSWORD_CHANGE_REQUIRED" | "ACCOUNT_LOCKED" | "ACCOUNT_DISABLED" | "NOT_FOUND" | "DUPLICATE" | "CONFLICT_MODIFIED" | "EXCEL_LIMIT_EXCEEDED" | "FILE_TOO_LARGE" | "INTERNAL_ERROR" | "INVALID_STATUS_CHANGE" | "REASON_REQUIRED" | "COMPANY_HAS_MEMBERS" | "COMPANY_NOT_ACTIVE" | "COMPANY_REQUIRED" | "USER_WITHDRAWN" | "MENU_DEPTH_EXCEEDED" | "MENU_PARENT_NOT_FOLDER" | "MENU_HAS_CHILDREN" | "MENU_SYSTEM_PROTECTED" | "MENU_BOARD_MANAGED" | "MENU_ORDER_MISMATCH" | "MENU_NOT_PAGE" | "CODE_SYSTEM_PROTECTED" | "CODE_GROUP_HAS_CODES" | "BOARD_MENU_EXISTS" | "BOARD_MENU_NOT_FOUND" | "REPLY_NOT_ALLOWED" | "COMMENT_NOT_ALLOWED" | "COMMENT_DEPTH_EXCEEDED" | "ATTACH_NOT_ALLOWED" | "ATTACH_COUNT_EXCEEDED" | "FILE_TYPE_NOT_ALLOWED" | "ROLE_REQUIRED" | "SELF_ROLE_CHANGE" | "SELF_DISABLE" | "PRIVILEGE_ESCALATION" | "LAST_SUPER_ADMIN" | "ROLE_NOT_USABLE" | "ROLE_NOT_EDITABLE" | "ROLE_IN_USE" | "ROLE_SYSTEM_PROTECTED";
        EmptyResponse: {
            /** @enum {boolean} */
            success: true;
            /** @enum {object|null} */
            data: never | null;
            error: components["schemas"]["NullError"];
        };
        LoginRequest: {
            loginId: string;
            /** Format: password */
            password: string;
        };
        Token: {
            accessToken: string;
            /**
             * @description Access Token 유효 시간(초)
             * @example 1800
             */
            expiresIn: number;
            /** @description true면 비밀번호 변경 화면으로 보낸다 (임시 비밀번호) */
            pwdChangeRequired: boolean;
        };
        TokenResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["Token"];
            error: components["schemas"]["NullError"];
        };
        RoleSummary: {
            roleCd: string;
            roleNm: string;
        };
        MenuNode: {
            /** Format: int64 */
            menuId: number;
            menuCd: string;
            menuNm: string;
            /** @enum {string} */
            menuTypeCd: "FOLDER" | "PAGE";
            /** @description 프론트 접두어(/react, /jsp, /ssr) 없는 경로 */
            menuUrl: string | null;
            icon: string | null;
            children: components["schemas"]["MenuNode"][];
        };
        Me: {
            /** Format: int64 */
            adminId: number;
            loginId: string;
            adminNm: string;
            email: string;
            mobileNo: string | null;
            deptNm: string | null;
            roles: components["schemas"]["RoleSummary"][];
            /** @description true면 모든 권한 (permissions는 비어 있다, ADR-0002) */
            superAdmin: boolean;
            /** @description 이번 로그인 직전의 로그인 일시 */
            lastLoginDt: string | null;
            lastLoginIp: string | null;
            pwdChangedDt: string | null;
            pwdChangeRequired: boolean;
            menus: components["schemas"]["MenuNode"][];
            /** @description 메뉴 코드 → 액션 목록 */
            permissions: {
                [key: string]: components["schemas"]["Action"][];
            };
            modDt: components["schemas"]["DateTime"];
        };
        MeResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["Me"];
            error: components["schemas"]["NullError"];
        };
        /** @enum {string} */
        Action: "READ" | "CREATE" | "UPDATE" | "DELETE" | "EXCEL" | "PRIVACY";
        UpdateMyInfoRequest: {
            adminNm: string;
            /** Format: email */
            email: string;
            mobileNo?: string | null;
            deptNm?: string | null;
            modDt: components["schemas"]["DateTime"];
        };
        ChangePasswordRequest: {
            /** Format: password */
            currentPassword: string;
            /**
             * Format: password
             * @description 1~20자 (docs/07-nonfunctional.md 1.1)
             */
            newPassword: string;
        };
        CodeGroupSummary: {
            groupCd: string;
            groupNm: string;
            codeCnt: number;
            systemYn: components["schemas"]["YnFlag"];
            useYn: components["schemas"]["YnFlag"];
        };
        CodeGroupListResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["CodeGroupSummary"][];
            error: components["schemas"]["NullError"];
        };
        CodeGroup: {
            groupCd: string;
            groupNm: string;
            description: string | null;
            systemYn: components["schemas"]["YnFlag"];
            useYn: components["schemas"]["YnFlag"];
            modDt: components["schemas"]["DateTime"];
        };
        CodeGroupResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["CodeGroup"];
            error: components["schemas"]["NullError"];
        };
        CodeGroupRequest: {
            groupCd: string;
            groupNm: string;
            description?: string | null;
            useYn: components["schemas"]["YnFlag"];
        };
        CodeGroupUpdateRequest: {
            groupNm: string;
            description?: string | null;
            useYn: components["schemas"]["YnFlag"];
            modDt: components["schemas"]["DateTime"];
        };
        CodeDetail: {
            groupCd: string;
            code: string;
            codeNm: string;
            sortOrd: number;
            description: string | null;
            useYn: components["schemas"]["YnFlag"];
            modDt: components["schemas"]["DateTime"];
        };
        CodeDetailListResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["CodeDetail"][];
            error: components["schemas"]["NullError"];
        };
        CodeDetailRequest: {
            code: string;
            codeNm: string;
            sortOrd: number;
            description?: string | null;
            useYn: components["schemas"]["YnFlag"];
        };
        CodeDetailUpdateRequest: {
            codeNm: string;
            sortOrd: number;
            description?: string | null;
            useYn: components["schemas"]["YnFlag"];
            modDt: components["schemas"]["DateTime"];
        };
        CodeItem: {
            /** @example SUSPENDED */
            code: string;
            /** @example 정지 */
            codeNm: string;
            sortOrd: number;
            useYn: components["schemas"]["YnFlag"];
        };
        CodeListResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["CodeItem"][];
            error: components["schemas"]["NullError"];
        };
        CodeMapResponse: {
            /** @enum {boolean} */
            success: true;
            /** @description 그룹코드 → 상세코드 목록 */
            data: {
                [key: string]: components["schemas"]["CodeItem"][];
            };
            error: components["schemas"]["NullError"];
        };
        MenuAdminNode: {
            /** Format: int64 */
            menuId: number;
            /** Format: int64 */
            parentMenuId: number | null;
            menuCd: string;
            menuNm: string;
            /** @enum {string} */
            menuTypeCd: "FOLDER" | "PAGE";
            menuUrl: string | null;
            depth: number;
            sortOrd: number;
            useYn: components["schemas"]["YnFlag"];
            systemYn: components["schemas"]["YnFlag"];
            boardAutoYn: components["schemas"]["YnFlag"];
            children: components["schemas"]["MenuAdminNode"][];
        };
        MenuTreeResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["MenuAdminNode"][];
            error: components["schemas"]["NullError"];
        };
        MenuDetail: {
            /** Format: int64 */
            menuId: number;
            /** Format: int64 */
            parentMenuId: number | null;
            parentMenuNm: string | null;
            menuCd: string;
            menuNm: string;
            /** @enum {string} */
            menuTypeCd: "FOLDER" | "PAGE";
            menuUrl: string | null;
            icon: string | null;
            depth: number;
            sortOrd: number;
            useYn: components["schemas"]["YnFlag"];
            systemYn: components["schemas"]["YnFlag"];
            boardAutoYn: components["schemas"]["YnFlag"];
            /** @description 사용 액션 (폴더 메뉴는 빈 배열) */
            actions: components["schemas"]["Action"][];
            modDt: components["schemas"]["DateTime"];
        };
        MenuDetailResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["MenuDetail"];
            error: components["schemas"]["NullError"];
        };
        MenuCreateRequest: {
            /**
             * Format: int64
             * @description 없으면 최상위 메뉴
             */
            parentMenuId?: number | null;
            menuCd: string;
            menuNm: string;
            /** @enum {string} */
            menuTypeCd: "FOLDER" | "PAGE";
            /** @description 화면 메뉴는 필수, 폴더 메뉴는 비운다 */
            menuUrl?: string | null;
            /** @description 화면 메뉴의 사용 액션 (READ는 항상 포함된다). 폴더 메뉴는 빈 배열 */
            actions: components["schemas"]["Action"][];
            icon?: string | null;
            useYn: components["schemas"]["YnFlag"];
        };
        MenuCreatedResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                /** Format: int64 */
                menuId: number;
            };
            error: components["schemas"]["NullError"];
        };
        MenuUpdateRequest: {
            menuNm: string;
            menuUrl?: string | null;
            actions: components["schemas"]["Action"][];
            icon?: string | null;
            useYn: components["schemas"]["YnFlag"];
            modDt: components["schemas"]["DateTime"];
        };
        RevokedRole: {
            /** Format: int64 */
            roleId: number;
            roleNm: string;
            actions: components["schemas"]["Action"][];
        };
        MenuUpdateResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                revokedRoles: components["schemas"]["RevokedRole"][];
            };
            error: components["schemas"]["NullError"];
        };
        MenuMoveRequest: {
            /**
             * Format: int64
             * @description 없으면 최상위로 옮긴다
             */
            parentMenuId?: number | null;
            modDt: components["schemas"]["DateTime"];
        };
        MenuOrderRequest: {
            orders: {
                /**
                 * Format: int64
                 * @description 없으면 최상위 메뉴들의 순서
                 */
                parentMenuId?: number | null;
                /** @description 그 상위 메뉴의 하위 메뉴 전부를 새 순서대로 */
                menuIds: number[];
            }[];
        };
        AvailabilityResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                available: boolean;
            };
            error: components["schemas"]["NullError"];
        };
        RoleListItem: {
            /** Format: int64 */
            roleId: number;
            roleCd: string;
            roleNm: string;
            description: string | null;
            /** @description 부여된 관리자 수 */
            adminCnt: number;
            systemYn: components["schemas"]["YnFlag"];
            useYn: components["schemas"]["YnFlag"];
        };
        RoleDetail: {
            /** Format: int64 */
            roleId: number;
            roleCd: string;
            roleNm: string;
            description: string | null;
            adminCnt: number;
            systemYn: components["schemas"]["YnFlag"];
            useYn: components["schemas"]["YnFlag"];
            /** @description 내가 가진 역할인지 */
            mine: boolean;
            /** @description 수정·권한 설정 가능 여부. 시스템 역할이거나 내 역할이면 false (슈퍼관리자는 내 역할도 true) */
            editable: boolean;
            regNm: string | null;
            regDt: components["schemas"]["DateTime"];
            modNm: string | null;
            modDt: components["schemas"]["DateTime"];
        };
        RoleListResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["RoleListItem"][];
            error: components["schemas"]["NullError"];
        };
        RoleDetailResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["RoleDetail"];
            error: components["schemas"]["NullError"];
        };
        RoleCreateRequest: {
            roleCd: string;
            roleNm: string;
            description?: string | null;
            useYn: components["schemas"]["YnFlag"];
        };
        RoleUpdateRequest: {
            roleNm: string;
            description?: string | null;
            useYn: components["schemas"]["YnFlag"];
            modDt: components["schemas"]["DateTime"];
        };
        RoleCopyRequest: {
            roleCd: string;
            roleNm: string;
        };
        RoleCreatedResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                /** Format: int64 */
                roleId: number;
            };
            error: components["schemas"]["NullError"];
        };
        RolePermissionNode: {
            /** Format: int64 */
            menuId: number;
            menuCd: string;
            menuNm: string;
            /** @enum {string} */
            menuTypeCd: "FOLDER" | "PAGE";
            depth: number;
            useYn: components["schemas"]["YnFlag"];
            /** @description 메뉴의 사용 액션 (폴더는 빈 배열) */
            actions: components["schemas"]["Action"][];
            /** @description 이 역할에 부여된 액션 */
            granted: components["schemas"]["Action"][];
            /** @description 내가 줄 수 있는 액션 (BR-05). 슈퍼관리자면 사용 액션 전체 */
            grantableActions: components["schemas"]["Action"][];
            children: components["schemas"]["RolePermissionNode"][];
        };
        RolePermissionTreeResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["RolePermissionNode"][];
            error: components["schemas"]["NullError"];
        };
        RolePermissionSaveRequest: {
            /** @description 권한을 줄 메뉴만, 메뉴별 최종 액션 목록 */
            permissions: {
                /** Format: int64 */
                menuId: number;
                actions: components["schemas"]["Action"][];
            }[];
            modDt: components["schemas"]["DateTime"];
        };
        PermissionChange: {
            /** Format: int64 */
            menuId: number;
            menuNm: string;
            action: components["schemas"]["Action"];
        };
        RolePermissionSaveResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                added: components["schemas"]["PermissionChange"][];
                removed: components["schemas"]["PermissionChange"][];
            };
            error: components["schemas"]["NullError"];
        };
        RoleAdmin: {
            /** Format: int64 */
            adminId: number;
            loginId: string;
            adminNm: string;
            deptNm: string | null;
            statusCd: string;
            statusNm: string | null;
            grantedDt: components["schemas"]["DateTime"];
        };
        RoleAdminListResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["RoleAdmin"][];
            error: components["schemas"]["NullError"];
        };
    };
    responses: {
        /** @description 입력값 오류 (VALIDATION_ERROR, INVALID_REQUEST) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 인증 필요 (UNAUTHORIZED, TOKEN_EXPIRED 등) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 권한 없음 (FORBIDDEN, PASSWORD_CHANGE_REQUIRED 등) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 대상 없음 (NOT_FOUND) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 중복·동시 수정·업무 규칙 위반 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 서버 오류 (INTERNAL_ERROR) */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        RoleId: number;
        MenuId: number;
        GroupCd: string;
        /** @description 페이지 번호 (1부터) */
        Page: number;
        /** @description 페이지 크기 */
        Size: 10 | 20 | 50;
        /** @description 필드,방향. 여러 개면 반복 (예: regDt,desc) */
        Sort: string[];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description 아이디 또는 비밀번호 오류 (LOGIN_FAILED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 잠금·사용중지 계정 (ACCOUNT_LOCKED, ACCOUNT_DISABLED) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그아웃 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 새 Access Token + 새 Refresh Token 쿠키 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description 만료·폐기·재사용된 Refresh Token (REFRESH_FAILED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 내 정보 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    updateMyInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMyInfoRequest"];
            };
        };
        responses: {
            /** @description 수정 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    changeMyPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description 변경 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getCodes: {
        parameters: {
            query?: {
                /** @description Y면 사용 안 함 코드도 포함 (이미 저장된 값 표시용) */
                includeUnused?: components["schemas"]["YnFlag"];
            };
            header?: never;
            path: {
                /** @example USER_STATUS */
                groupCd: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 정렬 순서대로 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getCodesByGroups: {
        parameters: {
            query: {
                /**
                 * @example [
                 *       "USER_STATUS",
                 *       "USER_TYPE"
                 *     ]
                 */
                groups: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 그룹코드별 상세코드 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeMapResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listCodeGroups: {
        parameters: {
            query?: {
                /** @description 그룹코드 또는 그룹코드명 부분 일치 */
                keyword?: string;
                useYn?: components["schemas"]["YnFlag"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 그룹코드 오름차순 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeGroupListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createCodeGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeGroupRequest"];
            };
        };
        responses: {
            /** @description 등록 완료 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getCodeGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupCd: components["parameters"]["GroupCd"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 그룹코드 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeGroupResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateCodeGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupCd: components["parameters"]["GroupCd"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeGroupUpdateRequest"];
            };
        };
        responses: {
            /** @description 수정 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteCodeGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupCd: components["parameters"]["GroupCd"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    listCodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupCd: components["parameters"]["GroupCd"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 상세코드 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeDetailListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupCd: components["parameters"]["GroupCd"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeDetailRequest"];
            };
        };
        responses: {
            /** @description 등록 완료 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    updateCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupCd: components["parameters"]["GroupCd"];
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeDetailUpdateRequest"];
            };
        };
        responses: {
            /** @description 수정 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupCd: components["parameters"]["GroupCd"];
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getMenuTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description depth, sortOrd 순서의 트리 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuTreeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    checkMenuCd: {
        parameters: {
            query: {
                menuCd: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 사용할 수 있으면 available=true */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createMenu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuCreateRequest"];
            };
        };
        responses: {
            /** @description 등록 완료 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuCreatedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    saveMenuOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuOrderRequest"];
            };
        };
        responses: {
            /** @description 저장 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menuId: components["parameters"]["MenuId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 메뉴 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuDetailResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateMenu: {
        parameters: {
            query?: {
                dryRun?: components["schemas"]["YnFlag"];
            };
            header?: never;
            path: {
                menuId: components["parameters"]["MenuId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuUpdateRequest"];
            };
        };
        responses: {
            /** @description 회수된(dryRun이면 회수될) 역할 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuUpdateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menuId: components["parameters"]["MenuId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    moveMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menuId: components["parameters"]["MenuId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuMoveRequest"];
            };
        };
        responses: {
            /** @description 이동 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    listRoles: {
        parameters: {
            query?: {
                /** @description 역할 코드·역할명 */
                keyword?: string;
                useYn?: components["schemas"]["YnFlag"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 역할 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreateRequest"];
            };
        };
        responses: {
            /** @description 등록 완료 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleCreatedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    checkRoleCd: {
        parameters: {
            query: {
                roleCd: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 사용할 수 있으면 available=true */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 역할 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDetailResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdateRequest"];
            };
        };
        responses: {
            /** @description 수정 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getRolePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 메뉴 트리. 화면 메뉴마다 사용 액션·부여된 액션·내가 줄 수 있는 액션 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolePermissionTreeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    saveRolePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolePermissionSaveRequest"];
            };
        };
        responses: {
            /** @description 추가·제거된 권한 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolePermissionSaveResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getRoleAdmins: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 관리자 목록 (부여일시 순) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleAdminListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    copyRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCopyRequest"];
            };
        };
        responses: {
            /** @description 복사 완료 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleCreatedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
}
