/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인. Access Token 응답 + Refresh Token 쿠키
         * @description 성공하면 Set-Cookie로 refreshToken(HttpOnly, SameSite=Strict, Path=/api/v1/auth/token)을 내려준다.
         *     같은 아이디의 기존 로그인(세션·토큰)은 모두 끊는다 (NF-LG-02).
         */
        post: operations["login"];
        /** 로그아웃. Refresh Token 폐기, 쿠키 삭제 */
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 토큰 재발급 (Refresh Token 쿠키 사용, 한 번 쓰면 교체) */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 정보 + 메뉴 트리 + 권한 목록 (메뉴 노출·버튼 활성화용) */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 내 정보 수정 */
        put: operations["updateMyInfo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 비밀번호 변경
         * @description 성공하면 이 관리자의 다른 로그인(세션·Refresh Token)을 모두 끊고,
         *     현재 로그인을 이어가도록 새 Access Token과 새 Refresh Token 쿠키를 준다.
         */
        put: operations["changeMyPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/common/codes/{groupCd}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 그룹코드의 상세코드 목록 (코드 콤보용) */
        get: operations["getCodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/common/codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 여러 그룹코드의 상세코드를 한 번에 */
        get: operations["getCodesByGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            /** @enum {object|null} */
            data: never | null;
            error: components["schemas"]["ErrorBody"];
        };
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** @description 화면에 그대로 보여 줄 수 있는 문장 */
            message: string;
            fieldErrors: components["schemas"]["FieldError"][];
        };
        FieldError: {
            /** @description 요청 필드 이름 */
            field: string;
            message: string;
        };
        /**
         * @description 성공 응답의 error는 항상 null
         * @enum {object|null}
         */
        NullError: never | null;
        PageMeta: {
            page: number;
            size: number;
            /** Format: int64 */
            totalCount: number;
            totalPages: number;
        };
        /** @enum {string} */
        YnFlag: "Y" | "N";
        /**
         * @description 한국 시간 일시, 초 단위, 시간대 표기 없음 (docs/06-api-spec.md 1절). 동시 수정 방지의 modDt도 이 형식
         * @example 2026-10-04T14:30:15
         */
        DateTime: string;
        /** @enum {string} */
        ErrorCode: "VALIDATION_ERROR" | "INVALID_REQUEST" | "UNAUTHORIZED" | "TOKEN_EXPIRED" | "REFRESH_FAILED" | "LOGIN_FAILED" | "FORBIDDEN" | "PASSWORD_CHANGE_REQUIRED" | "ACCOUNT_LOCKED" | "ACCOUNT_DISABLED" | "NOT_FOUND" | "DUPLICATE" | "CONFLICT_MODIFIED" | "EXCEL_LIMIT_EXCEEDED" | "FILE_TOO_LARGE" | "INTERNAL_ERROR" | "INVALID_STATUS_CHANGE" | "REASON_REQUIRED" | "COMPANY_HAS_MEMBERS" | "COMPANY_NOT_ACTIVE" | "COMPANY_REQUIRED" | "USER_WITHDRAWN" | "MENU_DEPTH_EXCEEDED" | "MENU_PARENT_NOT_FOLDER" | "MENU_HAS_CHILDREN" | "MENU_SYSTEM_PROTECTED" | "MENU_BOARD_MANAGED" | "MENU_ORDER_MISMATCH" | "MENU_NOT_PAGE" | "CODE_SYSTEM_PROTECTED" | "CODE_GROUP_HAS_CODES" | "BOARD_MENU_EXISTS" | "BOARD_MENU_NOT_FOUND" | "REPLY_NOT_ALLOWED" | "COMMENT_NOT_ALLOWED" | "COMMENT_DEPTH_EXCEEDED" | "ATTACH_NOT_ALLOWED" | "ATTACH_COUNT_EXCEEDED" | "FILE_TYPE_NOT_ALLOWED" | "ROLE_REQUIRED" | "SELF_ROLE_CHANGE" | "SELF_DISABLE" | "PRIVILEGE_ESCALATION" | "LAST_SUPER_ADMIN" | "ROLE_NOT_USABLE" | "ROLE_NOT_EDITABLE" | "ROLE_IN_USE" | "ROLE_SYSTEM_PROTECTED";
        EmptyResponse: {
            /** @enum {boolean} */
            success: true;
            /** @enum {object|null} */
            data: never | null;
            error: components["schemas"]["NullError"];
        };
        LoginRequest: {
            loginId: string;
            /** Format: password */
            password: string;
        };
        Token: {
            accessToken: string;
            /**
             * @description Access Token 유효 시간(초)
             * @example 1800
             */
            expiresIn: number;
            /** @description true면 비밀번호 변경 화면으로 보낸다 (임시 비밀번호) */
            pwdChangeRequired: boolean;
        };
        TokenResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["Token"];
            error: components["schemas"]["NullError"];
        };
        RoleSummary: {
            roleCd: string;
            roleNm: string;
        };
        MenuNode: {
            /** Format: int64 */
            menuId: number;
            menuCd: string;
            menuNm: string;
            /** @enum {string} */
            menuTypeCd: "FOLDER" | "PAGE";
            /** @description 프론트 접두어(/react, /jsp, /ssr) 없는 경로 */
            menuUrl: string | null;
            icon: string | null;
            children: components["schemas"]["MenuNode"][];
        };
        Me: {
            /** Format: int64 */
            adminId: number;
            loginId: string;
            adminNm: string;
            email: string;
            mobileNo: string | null;
            deptNm: string | null;
            roles: components["schemas"]["RoleSummary"][];
            /** @description true면 모든 권한 (permissions는 비어 있다, ADR-0002) */
            superAdmin: boolean;
            /** @description 이번 로그인 직전의 로그인 일시 */
            lastLoginDt: string | null;
            lastLoginIp: string | null;
            pwdChangedDt: string | null;
            pwdChangeRequired: boolean;
            menus: components["schemas"]["MenuNode"][];
            /** @description 메뉴 코드 → 액션 목록 */
            permissions: {
                [key: string]: components["schemas"]["Action"][];
            };
            modDt: components["schemas"]["DateTime"];
        };
        MeResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["Me"];
            error: components["schemas"]["NullError"];
        };
        /** @enum {string} */
        Action: "READ" | "CREATE" | "UPDATE" | "DELETE" | "EXCEL" | "PRIVACY";
        UpdateMyInfoRequest: {
            adminNm: string;
            /** Format: email */
            email: string;
            mobileNo?: string | null;
            deptNm?: string | null;
            modDt: components["schemas"]["DateTime"];
        };
        ChangePasswordRequest: {
            /** Format: password */
            currentPassword: string;
            /**
             * Format: password
             * @description 1~20자 (docs/07-nonfunctional.md 1.1)
             */
            newPassword: string;
        };
        CodeItem: {
            /** @example SUSPENDED */
            code: string;
            /** @example 정지 */
            codeNm: string;
            sortOrd: number;
            useYn: components["schemas"]["YnFlag"];
        };
        CodeListResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["CodeItem"][];
            error: components["schemas"]["NullError"];
        };
        CodeMapResponse: {
            /** @enum {boolean} */
            success: true;
            /** @description 그룹코드 → 상세코드 목록 */
            data: {
                [key: string]: components["schemas"]["CodeItem"][];
            };
            error: components["schemas"]["NullError"];
        };
    };
    responses: {
        /** @description 입력값 오류 (VALIDATION_ERROR, INVALID_REQUEST) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 인증 필요 (UNAUTHORIZED, TOKEN_EXPIRED 등) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 권한 없음 (FORBIDDEN, PASSWORD_CHANGE_REQUIRED 등) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 대상 없음 (NOT_FOUND) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 중복·동시 수정·업무 규칙 위반 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 서버 오류 (INTERNAL_ERROR) */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 페이지 번호 (1부터) */
        Page: number;
        /** @description 페이지 크기 */
        Size: 10 | 20 | 50;
        /** @description 필드,방향. 여러 개면 반복 (예: regDt,desc) */
        Sort: string[];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description 아이디 또는 비밀번호 오류 (LOGIN_FAILED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 잠금·사용중지 계정 (ACCOUNT_LOCKED, ACCOUNT_DISABLED) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그아웃 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 새 Access Token + 새 Refresh Token 쿠키 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description 만료·폐기·재사용된 Refresh Token (REFRESH_FAILED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 내 정보 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    updateMyInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMyInfoRequest"];
            };
        };
        responses: {
            /** @description 수정 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    changeMyPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description 변경 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getCodes: {
        parameters: {
            query?: {
                /** @description Y면 사용 안 함 코드도 포함 (이미 저장된 값 표시용) */
                includeUnused?: components["schemas"]["YnFlag"];
            };
            header?: never;
            path: {
                /** @example USER_STATUS */
                groupCd: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 정렬 순서대로 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getCodesByGroups: {
        parameters: {
            query: {
                /**
                 * @example [
                 *       "USER_STATUS",
                 *       "USER_TYPE"
                 *     ]
                 */
                groups: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 그룹코드별 상세코드 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeMapResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
